
post_install() {

    UPDATEUSER=archupdater
    ADIR=/home/$UPDATEUSER/archnews
    GITANEWS="https://github.com/mjiricka/archnews"

    TODAY=$(date +%F); useradd $UPDATEUSER -G systemd-journal --expiredate $TODAY -f -1 -m

    mkdir $ADIR
    git clone $GITANEWS $ADIR

    systemctl enable unattended-arch-upgrade.timer
    systemctl start unattended-arch-upgrade.timer
}

post_remove() {
    UPDATEUSER=archupdater
    ADIR=/home/$UPDATEUSER/archnews

    rm -Rf $ADIR
}

